CC      = clang
PROF    = -Wall -O -g -pg -ggdb
OBJDIR	= obj
LIBS = -lpthread -lz -lm -lrt -lssl -lcrypto -ldl -lcrypt -lquickmail  -lcotp -lqrencode -lpng -lhiredis -ljansson

GIT_VERSION := "$(shell git describe --dirty --always --tags)"
CUR_BUILD_DATE := "$(shell sh date.sh)"
GIT_URL := "$(shell sh giturl.sh)"

C_FLAGS = $(PROF) -std=c23 -fcommon -DMALLOC_STDLIB -fstack-protector  -m64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fwrapv -fPIC -fabi-version=2 -fno-omit-frame-pointer -DVERSION=\"$(GIT_VERSION)\" -DBUILD_DATE=\"$(CUR_BUILD_DATE)\" -DCOMMIT=\"$(GIT_URL)\" -MMD -MP

L_FLAGS =  $(PROF) $(LIBS)
EXE	= sent

C_FILES = \
    account/auth.c \
    account/auth_migrate.c \
    account/otp.c \
    account/account_notes.c \
    act_comm.c \
    act_enter.c \
    act_info.c \
    act_info2.c \
    act_move.c \
    act_obj.c \
    act_obj2.c \
    act_wiz.c \
    alias.c \
    auction.c \
    autowar.c \
    ban.c \
    bit.c \
    blueprint.c \
    boat.c \
    chat_rooms.c \
    church.c \
    comm.c \
    connection.c \
    connection_tcp.c \
    connection_tls.c \
    connection_websocket.c \
    const.c \
    protocol_layer.c \
    protocol_telnet.c \
    protocol_websocket.c \
    db.c \
    db2.c \
    drunk.c \
    dungeon.c \
    editors/areas/aedit.c \
    editors/blueprints/bpedit.c \
    editors/blueprints/bsedit.c \
    editors/commands/cmdedit.c \
    editors/dungeons/dngedit.c \
    editors/game_settings/gameedit.c \
    editors/help/hedit.c \
    editors/mobiles/medit.c \
    editors/objects/oedit.c \
    editors/projects/pedit.c \
    editors/random_strings/rsgedit.c \
    editors/reserved_vnums/reserved.c \
    editors/rooms/redit.c \
    editors/scripting/olc_mpcode.c \
    editors/ships/shedit.c \
    editors/socials/socialedit.c \
    editors/tokens/tedit.c \
    editors/wilderness/vledit.c \
    editors/wilderness/wedit.c \
    editors/common.c \
    effects.c \
    events.c \
    fight.c \
    fight2.c \
    gq.c \
    handler.c \
    help.c \
    house.c \
    html.c \
    hunt.c \
    interp.c \
    invasion.c \
    io/common.c \
    lookup.c \
    magic.c \
    magic2.c \
    magic_acid.c \
    magic_air.c \
    magic_astral.c \
    magic_blood.c \
    magic_body.c \
    magic_chaos.c \
    magic_cold.c \
    magic_cosmic.c \
    magic_dark.c \
    magic_death.c \
    magic_earth.c \
    magic_energy.c \
    magic_fire.c \
    magic_holy.c \
    magic_law.c \
    magic_light.c \
    magic_mana.c \
    magic_metal.c \
    magic_mind.c \
    magic_nature.c \
    magic_shock.c \
    magic_soul.c \
    magic_sound.c \
    magic_toxin.c \
    magic_water.c \
    mail.c \
    mccp.c \
    mem.c \
    mount.c \
    music.c \
    nanny.c \
    nanny/nanny_auth.c \
    nanny/nanny_menus.c \
    nanny/nanny_utils.c \
    note.c \
    olc.c \
    olc_act.c \
    olc_act2.c \
    olc_save.c \
    project.c \
    protocol.c \
    quest.c \
    redis_cache.c \
    async_cache.c \
    json_char.c \
    json_account.c \
    save.c \
    scan.c \
    script_commands.c \
    script_comp.c \
    script_const.c \
    script_expand.c \
    script_ifc.c \
    script_mpcmds.c \
    script_opcmds.c \
    script_rpcmds.c \
    script_tpcmds.c \
    script_vars.c \
    scripts.c \
    shoot.c \
    skills.c \
    special.c \
    staff.c \
    stats.c \
    string.c \
    storage.c \
    tables.c \
    tls.c \
    treasuremap.c \
    update.c \
    weather.c \
    wilds.c

O_FILES = $(patsubst %.c,$(OBJDIR)/%.o,$(C_FILES))
DEP_FILES = $(O_FILES:.o=.d)

all: $(EXE)

OBJ_DIRS_NEEDED := $(sort $(OBJDIR) $(patsubst %/,%,$(dir $(O_FILES))))
objdir:
	@echo "Creating object directories..."
	@mkdir -p $(OBJ_DIRS_NEEDED)
	@-chmod 775 $(OBJ_DIRS_NEEDED)

$(EXE): objdir $(O_FILES)
	@echo "Linking $(EXE)..."
	rm -f $(EXE)
	$(CC) -o $(EXE) $(O_FILES) $(L_FLAGS)
	-chmod 775 $(EXE)

$(OBJDIR)/%.o: %.c
	@echo "Building $<..."
	@mkdir -p $(dir $@)
	@$(CC) -c $(C_FLAGS) $< -o $@

-include $(DEP_FILES)

install: all
	@echo "Installing $(EXE) to ../"
	-cp -f $(EXE) ../
	@echo "Installation complete."

clean:
	@echo "Cleaning up..."
	@-rm -f $(O_FILES) $(DEP_FILES) $(EXE)
	@-rm -rf $(OBJDIR)

.PHONY: all install objdir clean